### ISSUE TITLE
[FEATURE] Use Yaml file as configuration input

### ISSUE THREAD

**Issue by MrWong99** [MrWong99/gitscanner#29]
### Is your feature request related to a problem? Please describe.
Currently we save our configuration in the database and expose it via REST. Additionaly most of the configuration can be set via start argumens. However since we want to be able to provide a wide variety of checks that developers can define and configure themselfes and the configuration should be as accessible as possible the current approach just isn't enough.

### Describe the solution you'd like
I want to have a configuration file in YAML format that is stored external to the application. This file should be able to configure anything within the application, even generic check configurations. Since the configuration should also be exposed via REST the current endpoints should work as before but when changing a configuration this change should be reflected in the configuration file and not the database. There should be, in fact, no more configuration in the database at all.

### Describe alternatives you've considered
An examplary file format:
```yaml
server:
  port: 443 # when this is set to anything but -1 (default) the app is started in server mode
  tls:
    certFile: /my/path/to/example.server.com.crt.pem # can contain a certificate chain
    certKey:  /my/path/to/example.server.com.key.pem

auth:
  ssh:
    privateKeyFile: /some/path/id_rsa
    keyPassphrase: abcd # should be encryptable
  basicAuth:
    username: blabla
    password: secur3 # should be encryptable

filters: # See feature request https://github.com/MrWong99/gitscanner/issues/30 about filters
  - name: commitTimePeriod
    from: 2020-05-15
    until: now
  - name: branchPattern
    pattern: origin/main|origin/feature_.*

checks:
  - name: SearchIllegalUnicodeCharacters
  - name: CheckCommiterEmail
    emailPattern: bob@github.com|alice@gitlab.com
  - name: CheckCommitSize
    thresholdBytes: 81920
    filters: # if present these filters override the global filters above
      - name: commitTimePeriod
        from: yesterday
        until: -1h
```
